Development
ialiev685/goit-markup-hw-04 pull request #1
Opened 2021-01-11 17:32 UTC by ialiev685

Добрый вечер! ДЗ № 4 выполнил.

2021-01-11 19:16 UTC, magom001 requested changes
не проходит валидацию https://validator.w3.org/nu/?doc=https%3A%2F%2Fialiev685.github.io%2Fgoit-markup-hw-04%2F

кнопки "Все", "веб-сайты"... не соответствуют макету

посмотри главную страницу на широком экране - верстка едет

на ховер кнопок нет теней

2021-01-11 19:16 UTC, magom001 commented on css/style.css
> +  --font-family-second: var(--name-font-family-Raleway);
красавчик

2021-01-11 19:16 UTC, magom001 commented on css/style.css
> +.product .item {
посмотри глазами: у тебя картинка уезжает за край карточки

2021-01-11 19:16 UTC, magom001 commented on css/style.css
> +.product .item:not(:nth-last-child(-n + 3)) {
почти всем сказал, скажу и тебе: это плохой подход. Убери одну карточки и посмотри, как поедет твоя верстка.

2021-01-11 20:57 UTC, ialiev685 commented on css/style.css
> +.product .item {
> не проходит валидацию https://validator.w3.org/nu/?doc=https%3A%2F%2Fialiev685.github.io%2Fgoit-markup-hw-04%2F
> 
> кнопки "Все", "веб-сайты"... не соответствуют макету
> 
> посмотри главную страницу на широком экране - верстка едет
> 
> на ховер кнопок нет теней

Все понял, кроме одного "посмотри главную страницу на широком экране - верстка едет". В чем она(страница ""студия) едет, можете прояснить. Отступы проверил. Не могу найти ошибку.

2021-01-12 19:34 UTC, ialiev685 commented
> не проходит валидацию https://validator.w3.org/nu/?doc=https%3A%2F%2Fialiev685.github.io%2Fgoit-markup-hw-04%2F
> 
> кнопки "Все", "веб-сайты"... не соответствуют макету
> 
> посмотри главную страницу на широком экране - верстка едет
> 
> на ховер кнопок нет теней

Исправил

2021-01-12 19:34 UTC, ialiev685 commented on css/style.css
> +.product .item {
Исправил

2021-01-12 21:17 UTC, ialiev685 commented on css/style.css
> +.product .item:not(:nth-last-child(-n + 3)) {
Прописал другой способ. Не идеальный, но подходит для данного случая.

2021-01-14 20:10 UTC, magom001 approved these changes
Только бордер карточек все равно неправильный. На макете вокруг картинок обводки нет. Исправь. В остальном ок.

2021-01-14 20:35 UTC, merged